### ISSUE TITLE
WebSocket class-based consumer should have a http_user class body option

### ISSUE THREAD

**Issue by pashinin** [andrewgodwin/channels#221]
Hi, I tried class based consumers, but `message.user` is always `AnonymousUser()`

```
class C(WebsocketConsumer):
    channel_session_user = True

    def connect(self, message, **kwargs):
        print(message.user)
```

I digged and it happens here: https://github.com/andrewgodwin/channels/blob/master/channels/auth.py#L40

Can you help with it?

**Comment by andrewgodwin** [comment]
You need to make sure the session cookies are coming through to Daphne - how have you set up your site to run? Are the websockets and the website where you're logged in on the same domain and port (e.g. `localhost` is different to `127.0.0.1`)?

**Comment by pashinin** [comment]
Whole test project is on daphne. Run with this:

```
daphne proj.asgi:channel_layer --port 8000 -b 0.0.0.0 -v2
```

plus a worker:

```
python manage.py runworker -v2
```

There were session cookies in `message.headers` when printed them if that's what needed.

**Comment by andrewgodwin** [comment]
Is there a session present in `message.session`, as well? It's worth comparing the session keys of HTTP and WS responses to work out what the difference is.

**Comment by andrewgodwin** [comment]
Err, make that `message.http_session`.

**Comment by pashinin** [comment]
Will check now

**Comment by pashinin** [comment]
That's what I get: no sessions (exceptions printed)
```
AnonymousUser
'Message' object has no attribute 'http_session'
'Message' object has no attribute 'session'
```

**Comment by andrewgodwin** [comment]
Oh, right, you haven't done the handoff from http session to channel session with the user object - the WebSocket endpoint doesn't have that yet. Let me retitle the issue to reflect that.

**Comment by andrewgodwin** [comment]
In the meantime, you need to wrap your connect in channel_session_user_from_http.

**Comment by pashinin** [comment]
Yeah, I thought this function will appear here. Thanks for the project. Waiting for fix.

**Comment by andrewgodwin** [comment]
Released in `0.16.1`.

**Comment by pydanny** [comment]
After upgrading to 0.16.1 I'm still having a problem with anonymous users and generics. I've tried running it using the following:

``` bash
python manage.py runserver
```
and
``` bash
python manage.py runworker -v2
daphne proj.asgi:channel_layer --port 8000 -b 0.0.0.0 -v2
```

My code is pretty simple:

``` python
from channels.generic.websockets import JsonWebsocketConsumer

class DiscussionConsumerServer(JsonWebsocketConsumer):

    channel_session_user = True

    def connect(self, message, **kwargs):        
        if message.user.is_anonymous():
            raise Exception("user is anonymous")
```

I followed the directions explicitly, and scanned the Channels code to make sure I was doing it correctly, but I'm still getting anonymous users. Maybe it's just me?

**Comment by andrewgodwin** [comment]
Swap `channel_session_user` for `http_user` and it should work. The commit added it as a seperate option as it has more implied behaviour.

**Comment by pydanny** [comment]
That did it! Thanks so much!
